### PR TITLE
Fix bug with empty SVG files

### LINKED ISSUE #3273: Empty SVG makes file manager inaccessible
**Affected version(s)**

Contao 4.9.17

**Description**

If an empty SVG file gets accidentally uploaded - or if you accidentally remove all content from the SVG via the back end editor (which is possible for SVG files by default), the file manager will get inaccessible with the following error and thus you cannot rectify the problem via the file manager anymore.

```
TypeError: strtolower() expects parameter 1 to be string, null given
#25 /vendor/contao/imagine-svg/src/Imagine.php(124): strtolower
#24 /vendor/contao/imagine-svg/src/Imagine.php(124): Contao\ImagineSvg\Imagine::doLoad
#23 /vendor/contao/imagine-svg/src/Imagine.php(59): Contao\ImagineSvg\Imagine::open
#22 /vendor/contao/image/src/Image.php(136): Contao\Image\Image::getDimensions
#21 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/File.php(261): Contao\File::__get
#20 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/File.php(301): Contao\File::__get
#19 /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php(2780): Contao\DC_Folder::generateTree
#18 /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php(2747): Contao\DC_Folder::generateTree
#17 /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php(2747): Contao\DC_Folder::generateTree
#16 /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php(400): Contao\DC_Folder::showAll
#15 /vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php(644): Contao\Backend::getBackendModule
#14 /vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php(167): Contao\BackendMain::run
#13 /vendor/contao/core-bundle/src/Controller/BackendController.php(48): Contao\CoreBundle\Controller\BackendController::mainAction
#12 /vendor/symfony/http-kernel/HttpKernel.php(158): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#11 /vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel::handle
#10 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
#9 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#8 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(477): Symfony\Component\HttpKernel\HttpCache\HttpCache::forward
#7 /vendor/symfony/framework-bundle/HttpCache/HttpCache.php(62): Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache::forward
#6 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(450): Symfony\Component\HttpKernel\HttpCache\HttpCache::fetch
#5 /vendor/contao/manager-bundle/src/HttpKernel/ContaoCache.php(47): Contao\ManagerBundle\HttpKernel\ContaoCache::fetch
#4 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(344): Symfony\Component\HttpKernel\HttpCache\HttpCache::lookup
#3 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(222): Symfony\Component\HttpKernel\HttpCache\HttpCache::handle
#2 /vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(103): Contao\ManagerBundle\HttpKernel\ContaoCache::handle
#1 /web/index.php(31): require
#0 /web/app.php(4): null
```

Curiously this error only happens in **prod**, not dev! However, in the `dev` env another, more visual error occurs when editing the empty SVG: the important part inputs will be visible (which they are usually not):

image

**Reproduction**

1. Create `files/empty.svg` with no content.
2. Set `APP_ENV` to `prod` (or do not define `APP_ENV` or disable the debug mode in the back end, if applicable).
3. Log into the Contao back end and visit the file manager.

### PR DESCRIPTION
**Pull request by ausi**
This should fix https://github.com/contao/contao/issues/3273

/cc @fritzmg

### CODE REVIEW

File: src/Imagine.php [hunk 1]
```diff
@@ -96,6 +96,10 @@ private function doLoad(string $data, MetadataBag $metadata): Image
             $data = gzdecode($data);
         }
 
+        if ('' === $data) {
+            throw new RuntimeException('An image can not be created from the empty string');
```
Comment (fritzmg) [inline src/Imagine.php]:
```suggestion
            throw new RuntimeException('An image cannot be created from an empty string');
```

**Review by fritzmg — CHANGES_REQUESTED** [review]

**Review by fritzmg — APPROVED** [review]
